-  name: Create Folders
   ansible.builtin.include_tasks:
     file: folder.yml
   loop: "{{ folders}}"

-  name: Create Multibranch Pipeline jobs
   ansible.builtin.include_tasks:
     file: mjob.yml
   loop: "{{ mjobs }}"

-  name: Create Multibranch Pipeline jobs
   ansible.builtin.include_tasks:
     file: sjob.yml
   loop: "{{ sjobs }}"
